on:
  - push
  - pull_request

name: Main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install -r requirements.txt
          pip install -e .
          invoke test
          invoke dist
      - if: ${{ matrix.python-version == '3.7' }}
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            dist/*
